[build]
  publish = "dist"
  command = "npm run build"

# Fallback for SPA routing - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
